### ISSUE TITLE
Console Spam and suggestion

### ISSUE THREAD

**Issue by Kahouk** [IlluzionzDev/Mobcoins#1]
Hey so each time players on our server use the /duel plugin which puts them into a 1v1 arena the console gets SPAMMED with an player interact event error and says failed the token redeem event or something similar. Also could you please make the commands /tokens give or set runnable through console since it would be a really nice feature for crates or a custom enchant that executed a cmd to give players mobcoins when killing mobs with a higher % 

Heres the exact error: 
[19:36:52 ERROR]: Could not pass event PlayerInteractEvent to MobCoins v1.0.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[server.jar:git-TacoSpigot-04511af6]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:306) [server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:273) [server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:269) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:818) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-TacoSpigot-04511af6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_271]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_271]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:849) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:890) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:785) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:684) [server.jar:git-TacoSpigot-04511af6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
Caused by: java.lang.NullPointerException
        at fun.pearce.mobcoins.core.listeners.RedeemListener.redeem(RedeemListener.java:50) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor172.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[server.jar:git-TacoSpigot-04511af6]

**Comment by Kahouk** [comment]
btw it doesnt harm the tps or anything, just spamms the shit out of console :s
